In [1]:
import array

In [2]:
arr1=array.array("i",[10,20,30,40])
print(arr1)

array('i', [10, 20, 30, 40])


In [3]:
arr1[2]

30

In [4]:
arr1[3]

40

In [5]:
for i in arr1:
    print(i)

10
20
30
40


In [6]:
for i in arr1:
    print(i,end=' ')

10 20 30 40 

In [7]:
arr1.insert(2,35)

In [8]:
print(arr1)

array('i', [10, 20, 35, 30, 40])


In [11]:
arr1.remove(20)
print(arr1)

array('i', [10, 35, 40])


In [12]:
arr1[2]=90
print(arr1)

array('i', [10, 35, 90])


In [15]:
sorted(arr1)
print(arr1)

array('i', [10, 35, 90])


In [1]:
### numpy


In [3]:
! pip install numpy

  Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)


In [4]:
import numpy as np

In [5]:
# creation

np1=np.array([10,20,30,40])
np2=np.array([50,60,70])

In [7]:
for i in np1:
    print(i,end=' ')

10 20 30 40 

In [9]:
# insertion

np.insert(np1,0,90)

array([90, 10, 20, 30, 40])

In [10]:
# deletion
np.delete(np1,0)

array([20, 30, 40])

In [11]:
#sorting
np3=np.array([4,3,6,7,8,9,5,555])


In [12]:
np3

array([  4,   3,   6,   7,   8,   9,   5, 555])

In [13]:
np.sort(np3)

array([  3,   4,   5,   6,   7,   8,   9, 555])

In [14]:
np.array_split(np3,3)

[array([4, 3, 6]), array([7, 8, 9]), array([  5, 555])]